In [1]:
import sqlite3

conn = sqlite3.connect("shopease.db")
cursor = conn.cursor()

print("Database created successfully!")

Database created successfully!

In [2]:
cursor.execute("""
CREATE TABLE customers (
    customer_id INTEGER PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    join_date DATE NOT NULL,
    is_premium BOOLEAN DEFAULT FALSE
);
""")

conn.commit()

In [3]:
cursor.execute("""
CREATE TABLE products ( 
    product_id    INT           PRIMARY KEY, 
    product_name  VARCHAR(100)  NOT NULL, 
    category      VARCHAR(50)   NOT NULL, 
    brand         VARCHAR(50)   NOT NULL, 
    unit_price    DECIMAL(10,2) NOT NULL  CHECK (unit_price > 0), 
    stock_qty     INT           NOT NULL  DEFAULT 0  CHECK (stock_qty >= 0) 
); 
""")

conn.commit()

In [4]:
cursor.execute("""
CREATE TABLE orders ( 
    order_id      INT           PRIMARY KEY, 
    customer_id   INT           NOT NULL, 
    order_date    DATE          NOT NULL, 
    status        VARCHAR(20)   NOT NULL  DEFAULT 'Pending' 
                  CHECK (status IN ('Pending','Shipped','Delivered','Cancelled')), 
    total_amount  DECIMAL(12,2) NOT NULL  CHECK (total_amount >= 0), 
     
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) 
);  
""")

conn.commit()

In [5]:
cursor.execute("""
CREATE TABLE order_items ( 
    item_id       INT           PRIMARY KEY, 
    order_id      INT           NOT NULL, 
    product_id    INT           NOT NULL, 
    quantity      INT           NOT NULL  CHECK (quantity > 0), 
    unit_price    DECIMAL(10,2) NOT NULL  CHECK (unit_price > 0), 
    discount_pct  DECIMAL(5,2)  DEFAULT 0 CHECK (discount_pct BETWEEN 0 AND 100), 
     
    FOREIGN KEY (order_id)   REFERENCES orders(order_id), 
    FOREIGN KEY (product_id) REFERENCES products(product_id) 
);   
""")

conn.commit()

In [6]:
cursor.executescript("""
INSERT INTO customers VALUES 
(101, 'Aarav',  'Sharma', 'aarav.s@email.com',  'Mumbai',    'Maharashtra', '2024-01-15', 
TRUE), 
(102, 'Priya',  'Patel',  'priya.p@email.com',  'Ahmedabad', 'Gujarat',     '2024-02-20', 
FALSE), 
(103, 'Rohan',  'Gupta',  'rohan.g@email.com',  'Delhi',     'Delhi',       '2024-03-10', 
TRUE), 
(104, 'Sneha',  'Reddy',  'sneha.r@email.com',  'Hyderabad', 'Telangana',   '2024-04-05', 
FALSE), 
(105, 'Vikram', 'Singh',  'vikram.s@email.com', 'Jaipur',    'Rajasthan',   '2024-05-12', 
TRUE), 
(106, 'Ananya', 'Iyer',   'ananya.i@email.com', 'Chennai',   'Tamil Nadu',  '2024-06-18', 
FALSE), 
(107, 'Karan',  'Mehta',  'karan.m@email.com',  'Pune',      'Maharashtra', '2024-07-22', 
TRUE), 
(108, 'Divya',  'Nair',   'divya.n@email.com',  'Kochi',     'Kerala',      '2024-08-30', 
FALSE); 
""")

conn.commit()

In [7]:
cursor.executescript("""
INSERT INTO products VALUES 
(201, 'Wireless Earbuds',     'Electronics', 'BoAt',          1499.00, 250), 
(202, 'Cotton T-Shirt',       'Clothing',    'Levis',         799.00,  500), 
(203, 'Smart Watch',          'Electronics', 'Noise',         2999.00, 150), 
(204, 'Running Shoes',        'Clothing',    'Nike',          4599.00, 120), 
(205, 'Bluetooth Speaker',    'Electronics', 'JBL',           3499.00, 200), 
(206, 'Bedsheet Set',         'Home',        'Spaces',        1299.00, 300), 
(207, 'Laptop Stand',         'Electronics', 'AmazonBasics',  899.00,  180), 
(208, 'Cushion Covers (Set)', 'Home',        'HomeCenter',    599.00,  400);  
""")

conn.commit()

In [8]:
cursor.executescript("""
INSERT INTO orders VALUES 
(1001, 101, '2024-08-01', 'Delivered',  4498.00), 
(1002, 102, '2024-08-03', 'Delivered',  799.00), 
(1003, 103, '2024-08-05', 'Shipped',    7498.00), 
(1004, 101, '2024-08-10', 'Delivered',  3499.00), 
(1005, 104, '2024-08-12', 'Cancelled',  2999.00), 
(1006, 105, '2024-08-15', 'Delivered',  5898.00), 
(1007, 106, '2024-08-18', 'Pending',    1299.00), 
(1008, 103, '2024-08-20', 'Delivered',  899.00), 
(1009, 107, '2024-08-25', 'Shipped',    6098.00), 
(1010, 108, '2024-08-28', 'Delivered',  1598.00);   
""")

conn.commit()

In [9]:
cursor.executescript("""
INSERT INTO order_items VALUES 
(5001, 1001, 201, 2, 1499.00, 0), 
(5002, 1001, 207, 1, 899.00,  10), 
(5003, 1002, 202, 1, 799.00,  0), 
(5004, 1003, 203, 1, 2999.00, 0), 
(5005, 1003, 204, 1, 4599.00, 5), 
(5006, 1004, 205, 1, 3499.00, 0), 
(5007, 1005, 203, 1, 2999.00, 0), 
(5008, 1006, 201, 1, 1499.00, 10), 
(5009, 1006, 204, 1, 4599.00, 5), 
(5010, 1007, 206, 1, 1299.00, 0), 
(5011, 1008, 207, 1, 899.00,  0), 
(5012, 1009, 205, 1, 3499.00, 0), 
(5013, 1009, 208, 2, 599.00,  15), 
(5014, 1010, 206, 1, 1299.00, 0), 
(5015, 1010, 208, 1, 599.00,  0); 

""")

conn.commit()

In [10]:
import pandas as pd

pd.read_sql("SELECT * FROM customers;", conn)

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
5,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
6,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
7,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

In [11]:
pd.read_sql("SELECT * FROM products;", conn)

,product_id,product_name,category,brand,unit_price,stock_qty
0,201,Wireless Earbuds,Electronics,BoAt,1499,250
1,202,Cotton T-Shirt,Clothing,Levis,799,500
2,203,Smart Watch,Electronics,Noise,2999,150
3,204,Running Shoes,Clothing,Nike,4599,120
4,205,Bluetooth Speaker,Electronics,JBL,3499,200
5,206,Bedsheet Set,Home,Spaces,1299,300
6,207,Laptop Stand,Electronics,AmazonBasics,899,180
7,208,Cushion Covers (Set),Home,HomeCenter,599,400

In [12]:
pd.read_sql("SELECT * FROM orders;", conn)

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered          4498
1      1002          102  2024-08-03  Delivered           799
2      1003          103  2024-08-05    Shipped          7498
3      1004          101  2024-08-10  Delivered          3499
4      1005          104  2024-08-12  Cancelled          2999
5      1006          105  2024-08-15  Delivered          5898
6      1007          106  2024-08-18    Pending          1299
7      1008          103  2024-08-20  Delivered           899
8      1009          107  2024-08-25    Shipped          6098
9      1010          108  2024-08-28  Delivered          1598

In [13]:
# Section A — SQL Basics (SELECT, Constraints, Primary Keys)*************************************************************** 

#Q1. Write a query to display all columns and rows from the customer's table. 
query = """
SELECT *
FROM customers;
"""

pd.read_sql(query, conn)

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
5,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
6,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
7,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

In [14]:
# Q2. Retrieve only the first_name, last_name, and city of all customers. 
query = """
SELECT first_name, last_name, city
FROM customers;
"""

pd.read_sql(query, conn)

  first_name last_name       city
0      Aarav    Sharma     Mumbai
1      Priya     Patel  Ahmedabad
2      Rohan     Gupta      Delhi
3      Sneha     Reddy  Hyderabad
4     Vikram     Singh     Jaipur
5     Ananya      Iyer    Chennai
6      Karan     Mehta       Pune
7      Divya      Nair      Kochi

In [15]:
#Q3. List all unique categories available in the products table
query = """
SELECT DISTINCT category
FROM products;
"""

pd.read_sql(query, conn)

      category
0  Electronics
1     Clothing
2         Home

In [16]:
# Q4. Identify the Primary Key of each table. Explain why a Primary Key must be unique and NOT NULL.

# Primary Key is a column having unique and not null elements, which is used to uniquely identifies each record in a table.
# It must be UNIQUE so that no two rows have the same identifier.
# It must be NOT NULL because every record must have a valid identifier.

# For each table primary key are:
# customer : customer_id
# products : product_id
# orders : order_id\
# order_items : item id

In [17]:
# Q5. What constraints are applied to the email column in the customers table? What would happen if you tried 
#     to insert a duplicate email? 

# Constraints which can apply for the column email would be:
#     1. NOT NULL :- email can not be empty.
#     2. UNIQUE :- So that duplicate email addresses are not allowed.

#     eg. :- " email VARCHAR(100) UNIQUE NOT NULL; "

# If we tried to insert a duplicate value, the database will raise a UNIQUE constraint violation error because a same email is already exist.

In [18]:
# Q6. Try inserting a product with unit_price = -50. What happens and which constraint prevents it? Write both 
#     the INSERT statement and explain the error. 

'''
query = """
INSERT INTO products
VALUES (
209,
'Test Product',
'Electronics',
'TestBrand',
-50,
100
);
"""

pd.read_sql(query, conn)

The insertion would be fail because we already applied a constrain in the table that unit_price would be greater than zero (CHECK (unit_price > 0)).
Since -50 is less than 0, the CHECK constraint is violated.
'''

'\nquery = """\nINSERT INTO products\nVALUES (\n209,\n\'Test Product\',\n\'Electronics\',\n\'TestBrand\',\n-50,\n100\n);\n"""\n\npd.read_sql(query, conn)\n\nThe insertion would be fail because we already applied a constrain in the table that unit_price would be greater than zero (CHECK (unit_price > 0)).\nSince -50 is less than 0, the CHECK constraint is violated.\n'

In [19]:
# Section B — Filtering & Optimization (WHERE, Indexes)*******************************************************************

In [20]:
# Q7. Retrieve all orders with status = 'Delivered'.
query = """
SELECT *
FROM orders
WHERE status = 'Delivered';
"""

pd.read_sql(query, conn)

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered          4498
1      1002          102  2024-08-03  Delivered           799
2      1004          101  2024-08-10  Delivered          3499
3      1006          105  2024-08-15  Delivered          5898
4      1008          103  2024-08-20  Delivered           899
5      1010          108  2024-08-28  Delivered          1598

In [21]:
# Q8. Find all products in the 'Electronics' category with a unit_price greater than ₹2000
query = """
SELECT *
FROM products
WHERE category = 'Electronics'
  AND unit_price > 2000;
"""

pd.read_sql(query, conn)

   product_id       product_name     category  brand  unit_price  stock_qty
0         203        Smart Watch  Electronics  Noise        2999        150
1         205  Bluetooth Speaker  Electronics    JBL        3499        200

In [22]:
# Q9. List all customers who joined in the year 2024 and belong to the state 'Maharashtra'
query = """
SELECT *
FROM customers
WHERE join_date BETWEEN '2024-01-01' AND '2024-12-31'
  AND state = 'Maharashtra';
"""

pd.read_sql(query, conn)

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1

In [23]:
# Q10. Find all orders placed between '2024-08-10' and '2024-08-25' (inclusive) that are NOT cancelled.
query = """
SELECT *
FROM orders
WHERE order_date BETWEEN '2024-08-10' AND '2024-08-25'
  AND status <> 'Cancelled';
"""

pd.read_sql(query, conn)

   order_id  customer_id  order_date     status  total_amount
0      1004          101  2024-08-10  Delivered          3499
1      1006          105  2024-08-15  Delivered          5898
2      1007          106  2024-08-18    Pending          1299
3      1008          103  2024-08-20  Delivered           899
4      1009          107  2024-08-25    Shipped          6098

In [24]:
# Q11. Explain what the index idx_orders_date does. How would it improve the performance of a query that 
#      filters orders by order_date? Write a sample query that would benefit from this index. 

# The index idx_orders_date is created on the order_date column. 
# It helps the database locate rows based on dates much faster without scanning the entire table.

# Without Index we need to scan to full table ans check every rows.

# Syntax:- SELECT * FROM order WHERE order_date BETWEEN '2024-08-01' AND '2024-08-31';

In [25]:
# Q12. If you run: SELECT * FROM customers WHERE YEAR(join_date) = 2024; — would the index on join_date 
#      be used? Explain why or why not, and rewrite the query to be index-friendly (SARGable). 

# No, the index would generally not be used efficiently. Because the database must first apply the YEAR() function to every row.
#     Since the indexed column is wrapped inside a function, the optimizer cannot directly use the index.

#     syntax:- SELECT * FROM customers WHERE join_date >= '2024-01-01'  AND join_date < '2025-01-01';

In [26]:
# Section C — Aggregation (GROUP BY, SUM, COUNT, AVG, MIN, MAX)***********************************************************

In [27]:
# Q13. Count the total number of orders in the orders table
query = """
SELECT COUNT(*) AS total_orders
FROM orders;
"""

pd.read_sql(query, conn)

   total_orders
0            10

In [28]:
# Q14. Find the total revenue (SUM of total_amount) from all 'Delivered' orders
query = """
SELECT SUM(total_amount) AS total_revenue
FROM orders
WHERE status = 'Delivered';
"""

pd.read_sql(query, conn)

   total_revenue
0          17191

In [29]:
# Q15. Calculate the average unit_price of products in each category
query = """
SELECT category,
       AVG(unit_price) AS avg_unit_price
FROM products
GROUP BY category;
"""

pd.read_sql(query, conn)

      category  avg_unit_price
0     Clothing          2699.0
1  Electronics          2224.0
2         Home           949.0

In [30]:
# Q16. For each order status, find the count of orders and total revenue. Sort by revenue descending.
query = """
SELECT status,
       COUNT(*) AS order_count,
       SUM(total_amount) AS total_revenue
FROM orders
GROUP BY status
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

      status  order_count  total_revenue
0  Delivered            6          17191
1    Shipped            2          13596
2  Cancelled            1           2999
3    Pending            1           1299

In [31]:
# Q17. Find the most expensive (MAX) and cheapest (MIN) product in each category.
query = """
SELECT category,
       MAX(unit_price) AS most_expensive,
       MIN(unit_price) AS cheapest
FROM products
GROUP BY category;
"""

pd.read_sql(query, conn)

      category  most_expensive  cheapest
0     Clothing            4599       799
1  Electronics            3499       899
2         Home            1299       599

In [32]:
# Q18. List all product categories where the average unit_price is greater than ₹2000
query = """
SELECT category,
       AVG(unit_price) AS avg_unit_price
FROM products
GROUP BY category
HAVING AVG(unit_price) > 2000;
"""

pd.read_sql(query, conn)

      category  avg_unit_price
0     Clothing          2699.0
1  Electronics          2224.0

In [33]:
# Section D — Joins & Relationships ****************************************************************************

In [34]:
#Q19. Write an INNER JOIN query to display each order along with the customer's first_name and last_name. 
#     Show: order_id, order_date, first_name, last_name, total_amount.

query = """
SELECT 
    o.order_id,
    o.order_date,
    c.first_name,
    c.last_name,
    o.total_amount
FROM orders o
INNER JOIN customers c
    ON o.customer_id = c.customer_id;
"""

pd.read_sql(query, conn)

   order_id  order_date first_name last_name  total_amount
0      1001  2024-08-01      Aarav    Sharma          4498
1      1002  2024-08-03      Priya     Patel           799
2      1003  2024-08-05      Rohan     Gupta          7498
3      1004  2024-08-10      Aarav    Sharma          3499
4      1005  2024-08-12      Sneha     Reddy          2999
5      1006  2024-08-15     Vikram     Singh          5898
6      1007  2024-08-18     Ananya      Iyer          1299
7      1008  2024-08-20      Rohan     Gupta           899
8      1009  2024-08-25      Karan     Mehta          6098
9      1010  2024-08-28      Divya      Nair          1598

In [35]:
# Q20. Using a LEFT JOIN, list ALL customers and their orders (if any). Customers with no orders should still 
#      appear with NULL values for order columns.

query = """
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    o.order_id,
    o.order_date,
    o.total_amount
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id;
"""

pd.read_sql(query, conn)

   customer_id first_name last_name  order_id  order_date  total_amount
0          101      Aarav    Sharma      1001  2024-08-01          4498
1          101      Aarav    Sharma      1004  2024-08-10          3499
2          102      Priya     Patel      1002  2024-08-03           799
3          103      Rohan     Gupta      1003  2024-08-05          7498
4          103      Rohan     Gupta      1008  2024-08-20           899
5          104      Sneha     Reddy      1005  2024-08-12          2999
6          105     Vikram     Singh      1006  2024-08-15          5898
7          106     Ananya      Iyer      1007  2024-08-18          1299
8          107      Karan     Mehta      1009  2024-08-25          6098
9          108      Divya      Nair      1010  2024-08-28          1598

In [36]:
#Q21. Write a query using JOINs across three tables (orders → order_items → products) to show: order_id, 
#   product_name, quantity, unit_price, and discount_pct for each order item. 

query = """
SELECT
    o.order_id,
    p.product_name,
    oi.quantity,
    oi.unit_price,
    oi.discount_pct
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id;
"""

pd.read_sql(query, conn)

    order_id          product_name  quantity  unit_price  discount_pct
0       1001      Wireless Earbuds         2        1499             0
1       1001          Laptop Stand         1         899            10
2       1002        Cotton T-Shirt         1         799             0
3       1003           Smart Watch         1        2999             0
4       1003         Running Shoes         1        4599             5
5       1004     Bluetooth Speaker         1        3499             0
6       1005           Smart Watch         1        2999             0
7       1006      Wireless Earbuds         1        1499            10
8       1006         Running Shoes         1        4599             5
9       1007          Bedsheet Set         1        1299             0
10      1008          Laptop Stand         1         899             0
11      1009     Bluetooth Speaker         1        3499             0
12      1009  Cushion Covers (Set)         2         599            15
13      1010          Bedsheet Set         1        1299             0
14      1010  Cushion Covers (Set)         1         599             0

In [37]:
#Q22. Explain the difference between LEFT JOIN and RIGHT JOIN with an example from this schema. When 
#     would you use a FULL OUTER JOIN? 

# In LEFT JOIN, it return all rows from the left table and matching rows from the right table.
# All the non matching rows show NULL values.
#     syntax:- SELECT * FROM customers c LEFT JOIN orders o ON c.customer_id = o.customer_id;

# In RIGHT JOIN, it will show all rows from the right table and matching rows from the left table.
# All the non matching rows show NULL values.
#     syntax:- SELECT * FROM customers c RIGHT JOIN orders o ON c.customer_id = o.customer_id;

# In FULL OUTER JOIN, it will display all rows from both the tables and the matching rows combined.
# Non-matching rows from either side filled with NULLs.
#     syntax:- Show all customers and all orders, including customers with no orders and orders without matching customers.

In [38]:
# Q23. Identify all Foreign Key relationships in the schema. Explain what would happen if you tried to insert an 
#    order with customer_id = 999 (which doesn't exist in customers). 

# A Foreign Key (FK) is a column in one table that refers to the Primary Key (PK) of another table.
#     The foreign key relationships in this schema are:
#     1. orders.customer_id → customers.customer_id
#     2. order_items.order_id → orders.order_id
#     3. order_items.product_id → products.product_id

# If we try to insert an order with customer_id = 999, the database will first check whether customer 999 exists in the customers table.
# Since no such customer exists in the sample data, the insertion will be rejected and a Foreign Key Constraint Violation error will occur.

In [39]:
# Section E — Advanced Concepts (CASE, ACID, Transactions) *********************************************************

In [40]:
# Q24. Write a query using CASE to classify products into price tiers: 
# • 'Budget'    → unit_price < 1000 
# • 'Mid-Range' → unit_price BETWEEN 1000 AND 3000 
# • 'Premium'   → unit_price > 3000 
# Display: product_name, unit_price, price_tier. 

query = """
SELECT
    product_name,
    unit_price,
    CASE
        WHEN unit_price < 1000 THEN 'Budget'
        WHEN unit_price BETWEEN 1000 AND 3000 THEN 'Mid-Range'
        ELSE 'Premium'
    END AS price_tier
FROM products;
"""

pd.read_sql(query, conn)

           product_name  unit_price price_tier
0      Wireless Earbuds        1499  Mid-Range
1        Cotton T-Shirt         799     Budget
2           Smart Watch        2999  Mid-Range
3         Running Shoes        4599    Premium
4     Bluetooth Speaker        3499    Premium
5          Bedsheet Set        1299  Mid-Range
6          Laptop Stand         899     Budget
7  Cushion Covers (Set)         599     Budget

In [41]:
# Q25. Using a CASE statement inside an aggregate function, count how many orders are 'Delivered' vs 'Not 
#      Delivered' (all other statuses). Display the result in a single row.

query = """
SELECT
    SUM(CASE WHEN status = 'Delivered' THEN 1 ELSE 0 END) AS Delivered_Orders,
    SUM(CASE WHEN status <> 'Delivered' THEN 1 ELSE 0 END) AS Not_Delivered_Orders
FROM orders;
"""

pd.read_sql(query, conn)

   Delivered_Orders  Not_Delivered_Orders
0                 6                     4

In [42]:
# Q26. Explain each letter of ACID: 
# • A – Atomicity 
# • C – Consistency 
# • I – Isolation 
# • D – Durability 
# Give a real-world example (e.g., bank transfer) showing why each property is important.


# ACID is a set of properties that ensures database transactions are processed reliably and maintain data integrity.
#     A – Atomicity:- Atomicity means a transaction is treated as a single unit of work. 
#                     Either all operations are completed successfully, or none of them are executed.
#     eg. :- A transaction is completed fully or not at all. 
#             If ₹1000 is deducted from Account A but cannot be added to Account B due to an error, 
#             the entire transaction is cancelled and the ₹1000 is returned to Account A.

                
#     C – Consistency:- Consistency ensures that a transaction takes the database from one valid state to another valid state
#                     while obeying all constraints and rules.
#     eg. :- A transaction must keep the database in a valid state. 
#           If the total balance of two accounts is ₹8000 before a transfer, 
#           it should still be ₹8000 after the transfer, ensuring no money is lost or created.

              
#     I – Isolation:- Isolation ensures that multiple transactions running simultaneously do not interfere with each other.
#     eg. :- If two users try to withdraw money from the same account simultaneously, 
#             each transaction is processed independently to prevent incorrect balances.
                

#     D – Durability:- Durability guarantees that once a transaction is committed, 
#                     its changes are permanently stored even if the system crashes afterward.
#     eg. :- after a bank transfer is confirmed, the updated balances remain stored even 
#             if the system crashes or loses power immediately afterward.

In [43]:
# Q27. Write a SQL transaction that does the following atomically: 
# 1. Insert a new order (order_id=1011, customer_id=102, today's date, 'Pending', 1598.00) 
# 2. Insert two order items for that order 
# 3. Update the stock_qty of the purchased products 
# 4. If any step fails, ROLLBACK the entire transaction. Otherwise, COMMIT. 
# Write the complete BEGIN...COMMIT/ROLLBACK block.



#  A transaction ensures that all operations are completed successfully as a single unit. 
#  If any operation fails, all changes are rolled back to maintain database consistency.
cursor.execute("BEGIN TRANSACTION")

try:
    # Step 1: Insert Order
    cursor.execute("""
    INSERT INTO orders
    VALUES (1011, 102, DATE('now'), 'Pending', 1598.00)
    """)

    # Step 2: Insert Order Items
    cursor.execute("""
    INSERT INTO order_items
    VALUES (5016, 1011, 202, 1, 799.00, 0)
    """)

    cursor.execute("""
    INSERT INTO order_items
    VALUES (5017, 1011, 208, 1, 599.00, 0)
    """)

    # Step 3: Update Stock Quantity
    cursor.execute("""
    UPDATE products
    SET stock_qty = stock_qty - 1
    WHERE product_id = 202
    """)

    cursor.execute("""
    UPDATE products
    SET stock_qty = stock_qty - 1
    WHERE product_id = 208
    """)

    # Step 4: Commit
    conn.commit()
    print("Transaction committed successfully!")

except Exception as e:
    conn.rollback()
    print("Transaction failed!")
    print(e)

Transaction committed successfully!